class SampleData{
  final List<Map<String, dynamic>> petData = [
    {
      'id': 1,
      'name': 'Milo',
      'species': 'Dog',
      'breed': 'Golden Retriever',
      'age': 3,
      'gender': 'Male',
      'size': 'Medium',
      'coatColor': 'Golden',
      'temperament': 'Friendly',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313_960_720.jpg',
      'location': 'San Francisco, CA',
      'adoptionStatus': 'Adopted',
    },
    {
      'id': 2,
      'name': 'Bella',
      'species': 'Dog',
      'breed': 'Labrador Retriever',
      'age': 2,
      'gender': 'Female',
      'size': 'Large',
      'coatColor': 'Chocolate',
      'temperament': 'Playful',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/06/03/17/42/dog-1437863_960_720.jpg',
      'location': 'New York, NY',
      'adoptionStatus': 'Available',
    },
    {
      'id': 3,
      'name': 'Charlie',
      'species': 'Dog',
      'breed': 'Poodle',
      'age': 4,
      'gender': 'Male',
      'size': 'Small',
      'coatColor': 'White',
      'temperament': 'Intelligent',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/02/19/15/46/dog-1210559_960_720.jpg',
      'location': 'Chicago, IL',
      'adoptionStatus': 'Available',
    },
    {
      'id': 4,
      'name': 'Lucy',
      'species': 'Dog',
      'breed': 'Beagle',
      'age': 1,
      'gender': 'Female',
      'size': 'Medium',
      'coatColor': 'Tri-color',
      'temperament': 'Energetic',
      'photoUrl': ' https://cdn.pixabay.com/photo/2016/02/19/15/46/dog-1210557_960_720.jpg',
      'location': 'Los Angeles, CA',
      'adoptionStatus': 'Available',
    },
    {
      'id': 5,
      'name': 'Max',
      'species': 'Dog',
      'breed': 'German Shepherd',
      'age': 2,
      'gender': 'Male',
      'size': 'Large',
      'coatColor': 'Black and Tan',
      'temperament': 'Loyal',
      'photoUrl': 'https://cdn.pixabay.com/photo/2015/06/08/15/05/urban-801869_960_720.jpg',
      'location': 'Seattle, WA',
      'adoptionStatus': 'Adopted',
    },
    {
      'id': 6,
      'name': 'Luna',
      'species': 'Dog',
      'breed': 'Husky',
      'age': 3,
      'gender': 'Female',
      'size': 'Large',
      'coatColor': 'Gray and White',
      'temperament': 'Playful',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/02/19/11/44/dog-1210004_960_720.jpg',
      'location': 'Austin, TX',
      'adoptionStatus': 'Available',
    },
    {
      'id': 7,
      'name': 'Oliver',
      'species': 'Cat',
      'breed': 'Maine Coon',
      'age': 2,
      'gender': 'Male',
      'size': 'Large',
      'coatColor': 'Tabby',
      'temperament': 'Gentle',
      'photoUrl': 'https://cdn.pixabay.com/photo/2017/11/09/21/41/cat-2934720_960_720.jpg',
      'location': 'Boston, MA',
      'adoptionStatus': 'Available',
    },
    {
      'id': 8,
      'name': 'Lily',
      'species': 'Cat',
      'breed': 'Persian',
      'age': 4,
      'gender': 'Female',
      'size': 'Medium',
      'coatColor': 'White',
      'temperament': 'Calm',
      'photoUrl': 'https://cdn.pixabay.com/photo/2015/11/16/14/43/cat-1045782_960_720.jpg',
      'location': 'San Diego, CA',
      'adoptionStatus': 'Available',
    },
    {
      'id': 9,
      'name': 'Leo',
      'species': 'Cat',
      'breed': 'Siamese',
      'age': 2,
      'gender': 'Male',
      'size': 'Medium',
      'coatColor': 'Seal Point',
      'temperament': 'Affectionate',
      'photoUrl': 'https://cdn.pixabay.com/photo/2015/11/16/14/43/cat-1045782_960_720.jpg',
      'location': 'Denver, CO',
      'adoptionStatus': 'Adopted',
    },
    {
      'id': 10,
      'name': 'Daisy',
      'species': 'Dog',
      'breed': 'Boxer',
      'age': 3,
      'gender': 'Female',
      'size': 'Large',
      'coatColor': 'Brindle',
      'temperament': 'Friendly',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313_960_720.jpg',
      'location': 'San Francisco, CA',
      'adoptionStatus': 'Adopted',
    },
    {
      'id': 11,
      'name': 'Rocky',
      'species': 'Dog',
      'breed': 'Bulldog',
      'age': 4,
      'gender': 'Male',
      'size': 'Medium',
      'coatColor': 'White and Brown',
      'temperament': 'Laid-back',
      'photoUrl': 'https://cdn.pixabay.com/photo/2018/03/31/06/31/dog-3277416_960_720.jpg',
      'location': 'Los Angeles, CA',
      'adoptionStatus': 'Available',
    },
    {
      'id': 12,
      'name': 'Coco',
      'species': 'Dog',
      'breed': 'Shih Tzu',
      'age': 2,
      'gender': 'Female',
      'size': 'Small',
      'coatColor': 'White and Tan',
      'temperament': 'Playful',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/02/26/16/32/dog-1224267_960_720.jpg',
      'location': 'New York, NY',
      'adoptionStatus': 'Available',
    },
    {
      'id': 13,
      'name': 'Simba',
      'species': 'Cat',
      'breed': 'Bengal',
      'age': 1,
      'gender': 'Male',
      'size': 'Medium',
      'coatColor': 'Spotted',
      'temperament': 'Active',
      'photoUrl': 'https://cdn.pixabay.com/photo/2017/11/09/21/41/cat-2934720_960_720.jpg',
      'location': 'Chicago, IL',
      'adoptionStatus': 'Available',
    },
    {
      'id': 14,
      'name': 'Sophie',
      'species': 'Dog',
      'breed': 'French Bulldog',
      'age': 1,
      'gender': 'Female',
      'size': 'Small',
      'coatColor': 'Fawn',
      'temperament': 'Playful',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/02/19/11/44/dog-1210004_960_720.jpg',
      'location': 'Los Angeles, CA',
      'adoptionStatus': 'Available',
    },
    {
      'id': 15,
      'name': 'Loki',
      'species': 'Cat',
      'breed': 'Ragdoll',
      'age': 3,
      'gender': 'Male',
      'size': 'Large',
      'coatColor': 'Blue',
      'temperament': 'Relaxed',
      'photoUrl': ' https://cdn.pixabay.com/photo/2016/07/10/21/47/cat-1508613_960_720.jpg',
      'location': 'San Francisco, CA',
      'adoptionStatus': 'Available',
    },
    {
      'id': 16,
      'name': 'Buddy',
      'species': 'Dog',
      'breed': 'Cocker Spaniel',
      'age': 2,
      'gender': 'Male',
      'size': 'Medium',
      'coatColor': 'Black',
      'temperament': 'Affectionate',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/02/16/15/05/dog-1209050_960_720.jpg',
      'location': 'New York, NY',
      'adoptionStatus': 'Available',
    },
    {
      'id': 17,
      'name': 'Molly',
      'species': 'Dog',
      'breed': 'Dalmatian',
      'age': 1,
      'gender': 'Female',
      'size': 'Medium',
      'coatColor': 'White with Black Spots',
      'temperament': 'Energetic',
      'photoUrl': 'https://cdn.pixabay.com/photo/2016/02/19/11/53/pug-1210023_960_720.jpg',
      'location': 'Chicago, IL',
      'adoptionStatus': 'Available',
    },
    {
      'id': 18,
      'name': 'Smokey',
      'species': 'Cat',
      'breed': 'Scottish Fold',
      'age': 2,
      'gender': 'Male',
      'size': 'Medium',
      'coatColor': 'Gray',
      'temperament': 'Curious',
      'photoUrl': 'https://cdn.pixabay.com/photo/2014/04/13/20/49/cat-323262_960_720.jpg',
      'location': 'Seattle, WA',
      'adoptionStatus': 'Adopted',
    },
    {
      'id': 19,
      'name': 'Oscar',
      'species': 'Cat',
      'breed': 'British Shorthair',
      'age': 3,
      'gender': 'Male',
      'size': 'Large',
      'coatColor': 'Blue',
      'temperament': 'Gentle',
      'photoUrl': 'https://cdn.pixabay.com/photo/2017/02/20/18/03/cat-2083492_960_720.jpg',
      'location': 'Austin, TX',
      'adoptionStatus': 'Available',
    },
    {
      'id': 20,
      'name': 'Bentley',
      'species': 'Dog',
      'breed': 'Great Dane',
      'age': 4,
      'gender': 'Male',
      'size': 'Extra Large',
      'coatColor': 'Black',
      'temperament': 'Gentle',
      'photoUrl': 'https://cdn.pixabay.com/photo/2017/02/20/18/03/cat-2083492_960_720.jpg',
      'location': 'Denver, CO',
      'adoptionStatus': 'Available',
    },
  ];
}